CREATE TABLE ORDER_TABLE
(
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID         BIGINT,
    TOTAL_PRICE     DECIMAL,      -- 价格，单位分
    ADDRESS         VARCHAR(1024),
    EXPRESS_COMPANY VARCHAR(16),
    EXPRESS_ID      BIGINT,
    STATUS          VARCHAR(16), -- PENDING 待付款 PAID 已付款 DELIVERED 物流中 RECEIVED 已收货
    CREATED_AT      TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT      TIMESTAMP NOT NULL DEFAULT NOW()
) DEFAULT CHARSET = utf8mb4;


CREATE TABLE `ORDER_GOODS`
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    GOODS_ID  BIGINT,
    ORDER_ID BIGINT,
    NUMBER   BIGINT -- 单位 分
) DEFAULT CHARSET = utf8mb4;